import { configureApiClient } from '@repo/api-client';
import { getEnphaseMock, getUsersMock } from '@repo/api-client/mocks';
import { cleanup } from '@testing-library/react';
import { setupServer } from 'msw/node';

import { i18n } from '../i18n/i18n.js';

/** API calls are answered by the MSW handlers generated by orval. */
export const server = setupServer(...getEnphaseMock(), ...getUsersMock());

configureApiClient({ baseUrl: 'http://api.test' });

beforeAll(async () => {
  server.listen({ onUnhandledRequest: 'error' });
  // French in tests: jsdom's navigator.language is `en`.
  await i18n.changeLanguage('fr');
});
afterEach(() => {
  cleanup();
  server.resetHandlers();
});
afterAll(() => server.close());
